"""Posts and Category Migrations

Revision ID: 2e22cfd6343b
Revises: 
Create Date: 2020-08-28 02:10:08.971005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e22cfd6343b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_created_date'), 'categories', ['created_date'], unique=False)
    op.create_index(op.f('ix_categories_updated_date'), 'categories', ['updated_date'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('content', sa.String(length=5000), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('feature_image', sa.LargeBinary(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_created_date'), 'posts', ['created_date'], unique=False)
    op.create_index(op.f('ix_posts_publish_date'), 'posts', ['publish_date'], unique=False)
    op.create_index(op.f('ix_posts_updated_date'), 'posts', ['updated_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_updated_date'), table_name='posts')
    op.drop_index(op.f('ix_posts_publish_date'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_date'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_categories_updated_date'), table_name='categories')
    op.drop_index(op.f('ix_categories_created_date'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
