"""Initial migrations

Revision ID: 6e00cf638fca
Revises: 
Create Date: 2020-08-27 00:55:48.807882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e00cf638fca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_timestamp'), 'categories', ['timestamp'], unique=False)
    op.create_index(op.f('ix_categories_updated'), 'categories', ['updated'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('content', sa.String(length=5000), nullable=False),
    sa.Column('category_id', sa.String(length=120), nullable=False),
    sa.Column('author_id', sa.String(length=120), nullable=False),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_publish_date'), 'posts', ['publish_date'], unique=False)
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    op.create_index(op.f('ix_posts_updated'), 'posts', ['updated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_updated'), table_name='posts')
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_index(op.f('ix_posts_publish_date'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_categories_updated'), table_name='categories')
    op.drop_index(op.f('ix_categories_timestamp'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
