"""role migrations

Revision ID: fd7fedc3ba13
Revises: e5c0e4587aee
Create Date: 2020-08-29 02:00:43.105024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7fedc3ba13'
down_revision = 'e5c0e4587aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_created_date'), 'role', ['created_date'], unique=False)
    op.create_index(op.f('ix_role_updated_date'), 'role', ['updated_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_updated_date'), table_name='role')
    op.drop_index(op.f('ix_role_created_date'), table_name='role')
    op.drop_table('role')
    # ### end Alembic commands ###
